// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbQxxxIlvgSX2rNmbJr2ZTQg9i2jd7EuI',
    appId: '1:304801457069:web:07420ce6f5009cef4ff724',
    messagingSenderId: '304801457069',
    projectId: 'soullink-8ed63',
    authDomain: 'soullink-8ed63.firebaseapp.com',
    storageBucket: 'soullink-8ed63.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3MrIviykGTfmaEYBrFmssXhsQIC-m7Mg',
    appId: '1:304801457069:android:f9e09117affd5ee94ff724',
    messagingSenderId: '304801457069',
    projectId: 'soullink-8ed63',
    storageBucket: 'soullink-8ed63.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhPb5cxKHGWhh5iHSUCT5OM7PoBvjg23Y',
    appId: '1:304801457069:ios:6354e82fb4cb86684ff724',
    messagingSenderId: '304801457069',
    projectId: 'soullink-8ed63',
    storageBucket: 'soullink-8ed63.firebasestorage.app',
    iosBundleId: 'com.example.soullink',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhPb5cxKHGWhh5iHSUCT5OM7PoBvjg23Y',
    appId: '1:304801457069:ios:6354e82fb4cb86684ff724',
    messagingSenderId: '304801457069',
    projectId: 'soullink-8ed63',
    storageBucket: 'soullink-8ed63.firebasestorage.app',
    iosBundleId: 'com.example.soullink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbQxxxIlvgSX2rNmbJr2ZTQg9i2jd7EuI',
    appId: '1:304801457069:web:dc416ae8fe29d0374ff724',
    messagingSenderId: '304801457069',
    projectId: 'soullink-8ed63',
    authDomain: 'soullink-8ed63.firebaseapp.com',
    storageBucket: 'soullink-8ed63.firebasestorage.app',
  );
}
